### ISSUE TITLE
Visualisation script specification does not match paper description for Fig 4 b) and c)

### ISSUE THREAD

**Issue by ermeel86** [jgabry/bayes-vis-paper#1]
The priors for $\beta_1$ and $beta_0$ specified in the manuscript on page 6 third paragraph do not match with the corresponding implementation in bayes-vis.R. In particular there we have
```
# Plot: prior predictive with weakly informative priors
beta0 <- rnorm(1, 1, 1)
beta1 <- rnorm(1, 1, 1)
```
Also the paper does not mention which prior is chosen for sigma in the same section 3.

**Comment by jgabry** [comment]
Thanks for letting us know. At some point we may have forgotten to update
the prior in the tex file after changing it in the R file and failed to
notice. I’ll fix that.

**Comment by jgabry** [comment]
Just fixed. Thanks again for pointing this out. In the acknowledgements section I added you to the people we thank, but I just put "GitHub user ermeel86":

https://github.com/jgabry/bayes-vis-paper/blob/master/bayes-vis.tex#L743

I'd prefer to replace that with your name if you're ok with that, but I didn't find it on your GitHub profile. Let me know what your prefer and thanks again.

**Comment by ermeel86** [comment]
Thank you. It’s a wonderful paper, from which I learned a lot. 

You can add my name, which is Eren Metin Elçi.

**Comment by jgabry** [comment]
Thanks!
